version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: cf-wp
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: cleverfiles
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    container_name: cf-db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cleverfiles
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cf-phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db

volumes:
  wordpress:
  db: